version: "3.8"

services:
  web:
    build: .
    container_name: coconut_app
    restart: always
    ports:
      - "443:8000"  # ✅ Redirect to HTTPS
    volumes:
      - sqlite_data:/app/db
      - static_volume:/app/static
      - pip_cache:/root/.cache/pip
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=coconut-app.onrender.com,127.0.0.1,localhost
      - CSRF_TRUSTED_ORIGINS=https://coconut-app.onrender.com
      - CORS_ALLOWED_ORIGINS=https://coconut-app.onrender.com
    command: ["gunicorn", "coconut_app.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3", "--timeout", "120"]

volumes:
  sqlite_data:
  static_volume:
  pip_cache:
