version: "3.8"

services:
  web:
    build: .
    container_name: coconut_app
    restart: always
    ports:
      - "8000:8000"  # Expose Django API to external access
    volumes:
      - sqlite_data:/app/db  # Persist SQLite database
      - static_volume:/app/static  # Persist static files
      - pip_cache:/root/.cache/pip  # Cache pip installations for faster rebuilds
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=0.0.0.0,127.0.0.1,localhost,192.168.1.38
      - CSRF_TRUSTED_ORIGINS=http://192.168.1.38,http://127.0.0.1

volumes:
  sqlite_data:  # Named volume for SQLite database
  static_volume:  # Named volume for static files
  pip_cache:  # Named volume for caching pip installations
