version: "3.8"

services:
  web:
    build: .
    container_name: coconut_app
    restart: always
    ports:
      - "8000:8000"  # Expose Django API to external access
    volumes:
      - sqlite_data:/app/db  # Persist SQLite database
      - static_volume:/app/static  # Persist static files
      - pip_cache:/root/.cache/pip  # Cache pip installations for faster rebuilds
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=coconut-app.onrender.com,127.0.0.1,localhost
      - CSRF_TRUSTED_ORIGINS=https://coconut-app.onrender.com,http://localhost:3000
volumes:
  sqlite_data:  # Named volume for SQLite database
  static_volume:  # Named volume for static files
  pip_cache:  # Named volume for caching pip installations
