version: "3.8"

services:
  web:
    build: .
    container_name: coconut_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - pip_cache:/root/.cache/pip
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=coconut-app-hrui.onrender.com,127.0.0.1,localhost
      - CSRF_TRUSTED_ORIGINS=https://coconut-app-hrui.onrender.com
      - CORS_ALLOWED_ORIGINS=https://coconut-app-hrui.onrender.com
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --chdir /app coconut_app.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"

volumes:
  static_volume:
  media_volume:
  pip_cache:
