# Generated by Django 4.2.16 on 2025-02-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coconut_calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
