# Generated by Django 4.2.16 on 2025-04-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coconut_calculation', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
