# Generated by Django 4.2.16 on 2025-02-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coconut_calculation', '0002_user_email_verification_sent_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verification_sent_at',
            new_name='password_reset_requested_at',
        ),
    ]
