# Generated by Django 4.2.16 on 2025-03-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coconut_calculation', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('id_proof_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('voter_id', 'Voter ID'), ('pan_card', 'PAN Card')], max_length=50)),
                ('id_proof_number', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
            ],
        ),
    ]
